# Introduction to NumPy

The most fundamental third-party package for scientific computing in Python is NumPy, which provides multidimensional **array** data types, along with associated functions and methods to manipulate them. Other third-party packages, including Pandas, use NumPy arrays as backends for more specialized data structures.


While Python comes with several container types (`list`,`tuple`,`dict`), NumPy's arrays are implemented closer to the hardware, and are therefore more **efficient** than the built-in types. This is particularly true for large data, for which NumPy scales much better than Python's built-in data structures.


NumPy arrays also retain a suite of associated functions and methods that allow for efficient *array-oriented* computing.


## Basics of Numpy arrays

We now turn our attention to the Numpy library, which forms the base layer for the entire Python *scientific stack*.  Once you have installed numpy, you can import it as

In [1]:
import numpy

though we will employ the conventional shorthand

In [2]:
import numpy as np

As mentioned above, the main object provided by numpy is a powerful array.  We'll start by exploring how the numpy array differs from Python lists.  We start by creating a simple list and an array with the same contents of the list:

In [5]:
lst = list(range(1000))
arr = np.arange(1000)

# Here's what the array looks like
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(arr)

numpy.ndarray

In [7]:
%timeit [i**2 for i in lst]

1000 loops, best of 3: 404 µs per loop


In [8]:
%timeit arr**2

The slowest run took 16.83 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.49 µs per loop


Elements of a one-dimensional array are indexed with square brackets, as with lists:

In [9]:
arr[5:10]

array([5, 6, 7, 8, 9])

In [10]:
arr[-1]

999

The first difference to note between lists and arrays is that arrays are **homogeneous**; i.e. all elements of an array must be of the same type.  In contrast, lists can contain elements of arbitrary type. For example, we can change the last element in our list above to be a string:

In [11]:
lst[0] = 'a string inside a list'
lst[:10]

['a string inside a list', 1, 2, 3, 4, 5, 6, 7, 8, 9]

but the same can not be done with an array, as we get an error message:

In [12]:
arr[0] = 'a string inside an array'

ValueError: invalid literal for int() with base 10: 'a string inside an array'

The information about the type of an array is contained in its *dtype* attribute:

In [13]:
arr.dtype

dtype('int64')

Once an array has been created, its dtype is fixed and it can only store elements of the same type.  For this example where the dtype is integer, if we store a floating point number it will be automatically converted into an integer:

In [14]:
arr[0] = 1.234
arr[:10]

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Above we created an array from an existing list; now let us now see other ways in which we can create arrays, which we'll illustrate next.  A common need is to have an array initialized with a constant value, and very often this value is 0 or 1 (suitable as starting value for additive and multiplicative loops respectively); `zeros` creates arrays of all zeros, with any desired dtype:

In [15]:
np.zeros(5, float)

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
np.zeros(3, int)

array([0, 0, 0])

In [17]:
np.zeros(3, complex)

array([ 0.+0.j,  0.+0.j,  0.+0.j])

and similarly for `ones`:

In [18]:
print('5 ones: {0}'.format(np.ones(5)))

5 ones: [ 1.  1.  1.  1.  1.]


If we want an array initialized with an arbitrary value, we can create an empty array and then use the fill method to put the value we want into the array:

In [19]:
a = np.empty(4)
a

array([ -2.31584178e+077,  -2.31584178e+077,  -2.31584178e+077,
         2.78134232e-309])

In [20]:
a.fill(5.5)
a

array([ 5.5,  5.5,  5.5,  5.5])

In [21]:
%timeit np.empty(1000)

The slowest run took 9.07 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.14 µs per loop


In [22]:
%timeit np.ones(1000)

The slowest run took 8.03 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 3.46 µs per loop


In [23]:
%timeit np.empty(1000).fill(1)

The slowest run took 17.69 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 1.9 µs per loop


In [24]:
%timeit np.ones(1000)*5.5

The slowest run took 8.40 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 5.63 µs per loop


We have seen how the `arange` function generates an array for a range of integers. Relatedly,  the `linspace` and `logspace` functions to create linearly and logarithmically-spaced **grids** respectively, with a fixed number of points and including both ends of the specified interval:

In [25]:
np.linspace(0, 1, num=5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [26]:
np.linspace(0, 1, endpoint=False, num=5)

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

In [27]:
np.logspace(1, 4, num=4)

array([    10.,    100.,   1000.,  10000.])

Finally, it is often useful to create arrays with random numbers that follow a specific **distribution**.  The `np.random` module contains a number of functions that can be used to this effect, for example this will produce an array of 5 random samples taken from a **standard normal** distribution (0 mean and variance 1):

$$f(x \mid \mu=0, \sigma=1) = \sqrt{\frac{1}{2\pi \sigma^2}} \exp\left\{ -\frac{x^2}{2\sigma^2} \right\}$$ 

In [28]:
np.random.randn(5)

array([-0.061234  , -0.53658247,  1.71227992, -1.63007725, -0.29624721])

whereas the following will also give 5 samples, but from a normal distribution with a mean of 9 and a standard deviation of 3:

In [29]:
norm10 = np.random.normal(loc=9, scale=3, size=10)

You can access the documentation for the `random` number generators, or any NumPy  function, using the `help` function.

In [48]:
help(np.random.exponential)

Help on built-in function exponential:

exponential(...) method of mtrand.RandomState instance
    exponential(scale=1.0, size=None)
    
    Exponential distribution.
    
    Its probability density function is
    
    .. math:: f(x; \frac{1}{\beta}) = \frac{1}{\beta} \exp(-\frac{x}{\beta}),
    
    for ``x > 0`` and 0 elsewhere. :math:`\beta` is the scale parameter,
    which is the inverse of the rate parameter :math:`\lambda = 1/\beta`.
    The rate parameter is an alternative, widely used parameterization
    of the exponential distribution [3]_.
    
    The exponential distribution is a continuous analogue of the
    geometric distribution.  It describes many common situations, such as
    the size of raindrops measured over many rainstorms [1]_, or the time
    between page requests to Wikipedia [2]_.
    
    Parameters
    ----------
    scale : float
        The scale parameter, :math:`\beta = 1/\lambda`.
    size : int or tuple of ints, optional
        Output shape.  If

More generally, you can search for NumPy help on a variety of topics, using the `lookfor` function. 

In [51]:
np.lookfor('distribution')

Search results for 'distribution'
---------------------------------
numpy.std
    Compute the standard deviation along the specified axis.
numpy.matlib.randn
    Return a random matrix with data from the "standard normal" distribution.
numpy.ma.MaskedArray.std
    Compute the standard deviation along the specified axis.
numpy.var
    Compute the variance along the specified axis.
numpy.nanstd
    Compute the standard deviation along the specified axis, while
numpy.nanvar
    Compute the variance along the specified axis, while ignoring NaNs.
numpy.convolve
    Returns the discrete, linear convolution of two one-dimensional sequences.
numpy.ma.std
    Compute the standard deviation along the specified axis.
numpy.ma.var
    Compute the variance along the specified axis.
numpy.matlib.rand
    Return a matrix of random values with given shape.
numpy.distutils.misc_util.Configuration.get_distribution
    Return the distutils distribution object for self.
numpy.distutils.command.install.ins

## Exercise: Random numbers

Generate a NumPy array of 1000 random numbers sampled from a Poisson distribution, with parameter `lam=5`. What is the modal value in the sample?

In [ ]:
# Write your answer here

## Indexing with other arrays

Above we saw how to index arrays with single numbers and slices, just like Python lists.  But arrays allow for a more sophisticated kind of indexing which is very powerful: you can index an array with another array, and in particular with an array of boolean (`bool`) values.  This is particluarly useful to extract information from an array that matches a certain condition.

Consider for example that in the array `norm10` we want to replace all values above 9 with the value 0.  We can do so by first finding the *mask* that indicates where this condition is `True` or `False`:

In [52]:
norm10

array([ 4.00502055,  0.        ,  0.        ,  0.        ,  8.46607839,
        6.72793676,  0.        ,  5.03909417,  3.85330655,  5.60654088])

In [53]:
mask = norm10 > 9
mask

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

Now that we have this mask, we can use it to return those values

In [54]:
norm10[mask]

array([], dtype=float64)

or to change their values

In [55]:
norm10[mask] = 0
norm10

array([ 4.00502055,  0.        ,  0.        ,  0.        ,  8.46607839,
        6.72793676,  0.        ,  5.03909417,  3.85330655,  5.60654088])

## Multidimensional Arrays

NumPy can create arrays of aribtrary dimensions, and all the methods illustrated in the previous section work with more than one dimension. For example, a list of lists can be used to initialize a two dimensional array:

In [57]:
samples_list = [[632, 1638, 569, 115], [433,1130,754,555]]
samples_array = np.array(samples_list)
samples_array.shape

(2, 4)

With two-dimensional arrays we start seeing the convenience of NumPy data structures: while a nested list can be indexed across dimensions using consecutive `[ ]` operators, multidimensional arrays support a more natural indexing syntax with a single set of brackets and a set of comma-separated indices:

In [58]:
samples_list[0][1]


1638

In [59]:
samples_array[0,1]

1638

Most of the array creation functions listed above can be passed multidimensional shapes. For example:

In [60]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [61]:
np.random.normal(10, 3, size=(2, 4))

array([[  9.21125685,  11.7926612 ,  10.9388272 ,  10.46856046],
       [  9.07070855,  11.12985651,   7.39608756,  10.63734614]])

In fact, an array can be **reshaped** at any time, as long as the total number of elements is unchanged.  For example, if we want a 2x4 array with numbers increasing from 0, the easiest way to create it is via the array's `reshape` method.

In [62]:
arr = np.arange(8).reshape(2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

With multidimensional arrays, you can also use slices, and you can mix and match slices and single indices in the different dimensions (using the same array as above):

In [63]:
arr[1, 2:4]

array([6, 7])

In [64]:
arr[:, 2]

array([2, 6])

If you only provide one index, then you will get the corresponding row.

In [65]:
arr[1]

array([4, 5, 6, 7])

Now that we have seen how to create arrays with more than one dimension, it's a good idea to look at some of the most useful **properties and methods** that arrays have.  The following provide basic information about the size, shape and data in the array:

In [66]:
print('Data type                :', samples_array.dtype)
print('Total number of elements :', samples_array.size)
print('Number of dimensions     :', samples_array.ndim)
print('Shape (dimensionality)   :', samples_array.shape)
print('Memory used (in bytes)   :', samples_array.nbytes)

Data type                : int64
Total number of elements : 8
Number of dimensions     : 2
Shape (dimensionality)   : (2, 4)
Memory used (in bytes)   : 64


Arrays also have many useful methods, some especially useful ones are:

In [67]:
print('Minimum and maximum             :', samples_array.min(), samples_array.max())
print('Sum, mean and standard deviation:', samples_array.sum(), samples_array.mean(), samples_array.std())

Minimum and maximum             : 115 1638
Sum, mean and standard deviation: 5826 728.25 435.545563059


For these methods, the above operations area all computed on all the elements of the array.  But for a multidimensional array, it's possible to do the computation along a single dimension, by passing the `axis` parameter; for example:

In [68]:
samples_array.sum(axis=0)

array([1065, 2768, 1323,  670])

In [69]:
samples_array.sum(axis=1)

array([2954, 2872])

As you can see in this example, the value of the `axis` parameter is the dimension which will be *consumed* once the operation has been carried out.  This is why to sum along the rows we use `axis=0`.  

This can be easily illustrated with an example that has more dimensions; we create an array with 4 dimensions and shape `(3,4,5,6)` and sum along the axis index 2.  That consumes the dimension whose length was 5, leaving us with a new array that has shape `(3,4,6)`:

In [70]:
np.zeros((3,4,5,6)).sum(2).shape

(3, 4, 6)

Another widely used property of arrays is the `.T` attribute, which allows you to access the transpose of the array:

In [71]:
samples_array.T

array([[ 632,  433],
       [1638, 1130],
       [ 569,  754],
       [ 115,  555]])

Which is the equivalent of calling NumPy's `transpose` function:

In [72]:
np.transpose(samples_array)

array([[ 632,  433],
       [1638, 1130],
       [ 569,  754],
       [ 115,  555]])

There is a wide variety of methods and properties of arrays.       

In [73]:
[attr for attr in dir(samples_array) if not attr.startswith('__')]

['T',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'ctypes',
 'cumprod',
 'cumsum',
 'data',
 'diagonal',
 'dot',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'getfield',
 'imag',
 'item',
 'itemset',
 'itemsize',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'newbyteorder',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']

### Exercises: Matrix Creation

Generate the following structure as a numpy array, without typing the values by hand. Then, create another array containing just the 2nd and 4th rows.

        [[1,  6, 11],
         [2,  7, 12],
         [3,  8, 13],
         [4,  9, 14],
         [5, 10, 15]]

In [97]:
# Write your answer here

Create a **tridiagonal** matrix with 5 rows and columns, with 1's on the diagonal and 2's on the off-diagonal.

In [78]:
# Write your answer here

## Array Operations

Arrays support all regular arithmetic operators, and NumPy also contains a complete collection of basic mathematical functions that operate on arrays.  It is important to remember that in general, all operations with arrays are applied **element-wise**, that is, applied to each element of the array.  

Consider for example:

In [80]:
sample1, sample2 = np.array([632, 1638, 569, 115]), np.array([433,1130,754,555])
sample_sum = sample1 + sample2

print('{0} + {1} = {2}'.format(sample1, sample2, sample_sum))

[ 632 1638  569  115] + [ 433 1130  754  555] = [1065 2768 1323  670]


This includes the multiplication operator -- it does *not* perform matrix multiplication, as is the case in Matlab, for example:

In [81]:
print('{0} X {1} = {2}'.format(sample1, sample2, sample1*sample2))

[ 632 1638  569  115] X [ 433 1130  754  555] = [ 273656 1850940  429026   63825]


While this implies that the dimension of the arrays for each operation must match in size, numpy will **broadcast** dimensions when possible.  For example, suppose that you want to add the number 1.5 to each element `arr1`. One approach is to use the `ones` function to match the dimension of the array.

In [83]:
sample1 + 1.5*np.ones(4)

array([  633.5,  1639.5,   570.5,   116.5])

But thanks to numpy's broadcasting rules, the following is equally valid:

In [ ]:
sample1 + 1.5

In this case, numpy looked at both operands and saw that the first was a one-dimensional array of length 4 and the second was a scalar, considered a zero-dimensional object. The broadcasting rules allow numpy to:

* *create* new array of length 1 
* *extend* the array to match the size of the corresponding array

So in the above example, the scalar 1.5 is effectively cast to a 1-dimensional array of length 1, then stretched to length 4 to match the dimension of `arr1`. After this, element-wise addition can proceed as now both operands are one-dimensional arrays of length 4.

This broadcasting behavior is powerful, especially because when NumPy broadcasts to create new dimensions or to stretch existing ones, it doesn't actually replicate the data.  In the example above the operation is carried *as if* the 1.5 was a 1-d array with 1.5 in all of its entries, but no actual array was ever created.  This saves memory and improves the **performance** of operations.

When broadcasting, NumPy compares the sizes of each dimension in each operand. It starts with the trailing dimensions, working forward and creating dimensions as needed to accomodate the operation. Two dimensions are considered compatible for operation when:

* they are equal in size
* one is scalar (or size 1)

If these conditions are not met, an exception is thrown, indicating that the arrays have incompatible shapes. 

In [84]:
sample1 + np.array([7,8])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

Let's create a 1-dimensional array and add it to a 2-dimensional array, to illustrate broadcasting:

In [88]:
b = np.array([10, 20, 30, 40])
bcast_sum = sample1 + b

print('{0}\n\n+ {1}\n{2}\n{3}'.format(sample1, b, '-'*21, bcast_sum))

[ 632 1638  569  115]

+ [10 20 30 40]
---------------------
[ 642 1658  599  155]


What if we wanted to add `[-100, 100]` to the rows of `sample1`?  Direct addition will not work:

In [89]:
c = np.array([-100, 100])
sample1 + c

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

Remember that matching begins at the **trailing** dimensions. Here, `c` would need to have a trailing dimension of 1 for the broadcasting to work.  We can augment arrays with dimensions on the fly, by indexing it with a `np.newaxis` object, which adds an "empty" dimension:

In [90]:
cplus = c[:, np.newaxis]
cplus

array([[-100],
       [ 100]])

This is exactly what we need, and indeed it works:

In [91]:
sample1 + cplus

array([[ 532, 1538,  469,   15],
       [ 732, 1738,  669,  215]])

For the full broadcasting rules, please see the official Numpy docs, which describe them in detail and with more complex examples.

### Exercises: Array manipulation

Divide each column of the array:

        a = np.arange(25).reshape(5, 5)

elementwise with the array `b = np.array([1., 5, 10, 15, 20])`.

In [ ]:
# Write your answer here

Generate a 10 x 3 array of random numbers (in range [0,1]). For each row, pick the number closest to 0.5.

*Hints*:

* Use `abs` and `argsort` to find the column `j` closest for each row.
* Use "fancy" indexing to extract the numbers.


In [ ]:
# Write your answer here

## Linear Algebra

Numpy includes a linear algebra submodule, along with a suite of `array` methods for performing linear algebra. For example, the `dot` method performs an inner (dot) product on vectors and matrices:

In [98]:
v1 = np.array([2, 3, 4])
v2 = np.array([1, 0, 1])

v1.dot(v2)

6

Equivalently, we can use the `dot` function:

In [99]:
np.dot(v1, v2)

6

When performing regular matrix-vector multiplication, note that NumPy makes no distinction between row and column vectors *per se* and simply verifies that the dimensions match the required rules of matrix multiplication, in this case we have a $2 \times 3$ matrix multiplied by a 3-vector, which produces a 2-vector:

In [100]:
A = np.arange(6).reshape(2, 3)

A.dot(v1)

array([11, 38])

For matrix-matrix multiplication, the same dimension-matching rules must be satisfied, e.g. consider the difference between $A \times A^T$:

In [101]:
A.dot(A.T)

array([[ 5, 14],
       [14, 50]])

and $A^T \times A$:

In [102]:
A.T.dot(A)

array([[ 9, 12, 15],
       [12, 17, 22],
       [15, 22, 29]])

Beyond inner products, the `numpy.linalg` module includes functions for calculating determinants, matrix norms, Cholesky decomposition, eigenvalue and singular value decompositions, and more.  

Additional linear algebra tools are available in SciPy's linear algebra library, `scipy.linalg`. It includes the majority of the tools in the classic LAPACK libraries as well as functions to operate on sparse matrices.  

## Reading and writing data

NumPy lets you save and retrive data structures to and from files on a local or remote storage, in either **text** or **binary** formats. Which format is appropriate depends on which tradeoff that you are willing to make:

* **Text mode**: occupies more space, precision can be lost (if not all digits are written to disk), but is readable and editable by hand with a text editor.  Storage is limited to one- and two-dimensional arrays.

* **Binary mode**: compact and exact representation of the data in memory, can't be read or edited by hand.  Arrays of any size and dimensionality can be saved and read without loss of information.

First, let's see how to read and write arrays in text mode.  The `np.savetxt` function saves an array to a text file, with options to control the precision, separators and even adding a header:

In [103]:
arr = np.arange(10).reshape(2, 5)
np.savetxt('test.out', arr, fmt='%.2e', header="My dataset")

In [104]:
!cat test.out

# My dataset
0.00e+00 1.00e+00 2.00e+00 3.00e+00 4.00e+00
5.00e+00 6.00e+00 7.00e+00 8.00e+00 9.00e+00


And this same type of file can then be read with the matching `np.loadtxt` function:

In [105]:
arr2 = np.loadtxt('test.out')
arr2

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

For binary data, we use either `np.save` or `np.savez`.  The first saves a single array to a file with `.npy` extension, while the latter can be used to save a *group* of arrays into a single file with `.npz` extension.  The files created with these routines can then be read with the `np.load` function.

Let us first see how to use the simpler `np.save` function to save a single array:

In [106]:
np.save('test.npy', arr2)

This can be read back:

In [107]:
arr2n = np.load('test.npy')

And we can confirm that they are equal:

In [108]:
np.any(arr2 - arr2n)

False

Now let us see how the `np.savez` function works.  

It expects both a filename and either a sequence of arrays or a set of key-value pairs.  If arrays are passed, the `savez` will automatically name the saved arrays in the archive as `arr_0`, `arr_1`, ...

In [109]:
np.savez('test.npz', arr, arr2)
arrays = np.load('test.npz')
arrays.files

['arr_0', 'arr_1']

Alternatively, if we explicitly name the arrays using keyword arguments:

In [111]:
np.savez('test.npz', foo=arr, bar=arr2)
arrays = np.load('test.npz')
arrays.files

['bar', 'foo']

The object returned by `np.load` from an `.npz` file works like a dictionary, though you can also access its constituent files by attribute using its special `.f` field; this is best illustrated with an example with the `arrays` object from above:

In [ ]:
# First row of array
arrays['array1'][0]

Equivalently:

In [ ]:
arrays.f.array1[0]

This `.npz` format is a very convenient way to package compactly and without loss of information, into a single file, a group of related arrays that pertain to a specific problem.  At some point, however, the complexity of your dataset may be such that the optimal approach is to use one of the standard formats in scientific data processing that have been designed to handle complex datasets, such as NetCDF or HDF5.  

## Guided Exercise: Structured Arrays 

Import the `microbiome.csv` dataset in the `data/microbiome` directory using NumPy's `loadtxt` function. This will take some experimentation; use the built-in help to get hints!

In [ ]:
# Write answer here

---

In [2]:
from IPython.core.display import HTML
def css_styling():
    styles = open("styles/custom.css", "r").read()
    return HTML(styles)
css_styling()